name: 🔖 deployer

on:
  release:
    types:
      - 'created'

jobs:
  deploy:
    name: deploy server
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: deploy
        run: |
          sudo docker pull ghcr.io/rooftop-msa/identity:${{ github.ref_name }}
          sudo docker ps -aq | xargs docker stop | xargs docker rm
          sudo docker run -d -p 8080:8080 --cpus 2 --memory 2G ghcr.io/rooftop-msa/identity:${{ github.ref_name }}
